# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1a0d0ed0e377b3d058c8c5a7f0a5eb9d06cf8e90a0ab124a853aaa4cf1b7626b0ca2019d8c957e0f8e95411b31314e86e06572fa1ba25e66c3cf8c012dbc5966

test:
  secret_key_base: 5650c2a134575389c62241e217fbc5fa1532db8f3f0bc0a1d37bdb981a2fa4a19ce12756d0355967a973a5d6e120bee129b8bb2a23a78d663cfe012ddb0a10c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
